export const DEMO_COUPONS = [
  {
    id: 1,
    code: "SUMMER25",
    description: "Summer Sale 25% Off",
    discountType: "percentage",
    discountValue: 25,
    minPurchase: 50,
    maxDiscount: 100,
    usageLimit: 100,
    usedCount: 45,
    startDate: "2024-06-01",
    endDate: "2024-08-31",
    status: "active",
  },
  {
    id: 2,
    code: "FLAT50",
    description: "Flat $50 Off",
    discountType: "fixed",
    discountValue: 50,
    minPurchase: 200,
    maxDiscount: null,
    usageLimit: 50,
    usedCount: 50,
    startDate: "2024-01-01",
    endDate: "2024-12-31",
    status: "expired",
  },
  {
    id: 3,
    code: "NEWUSER",
    description: "New User Discount",
    discountType: "percentage",
    discountValue: 15,
    minPurchase: 0,
    maxDiscount: 50,
    usageLimit: 500,
    usedCount: 234,
    startDate: "2024-01-01",
    endDate: "2025-12-31",
    status: "active",
  },
];
